services:
  postgres:
    image: postgres:15
    container_name: litellm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: litellm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - litellm-network

  litellm:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: litellm-proxy
    ports:
      - "4000:4000"
    command: 
      - sh
      - -c
      - poetry run litellm --config /app/config.yaml
    environment:
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/litellm
      LITELLM_MASTER_KEY: ${LITELLM_MASTER_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - litellm-network
    volumes:
      - ./examples/proxy/config.yaml:/app/config.yaml
      - ./pyproject.toml:/app/pyproject.toml

networks:
  litellm-network:
    driver: bridge

volumes:
  postgres_data: 